### ISSUE TITLE
Workout graph cut after screen rotation

### ISSUE THREAD

**Issue by karlacio** [dvmarinoff/Auuki#212]
Hi,

I usually use Auuki in with my phone placed in vertical.

Sometime I have screen rotation active and if I accidentally switch to lanscape mode, when I return back in vertical mode, the workout graph will be cut on the right side.

After the cut, Auuki shows correctly the graph in landscape mode.
In vertical mode it remains always cut (even if i load a new workout).

The solution is to kill and restart the the web page (or app).

I attach some screenshot to show the problem:

![vertical](https://github.com/user-attachments/assets/32628ad0-d00f-465b-93b0-d025b0d4663e)
![land](https://github.com/user-attachments/assets/ed9127c6-7ed5-4c8c-9d57-a6b6dca9d003)

Carlo.

**Comment by dvmarinoff** [comment]
Thanks for the report, I've been noticing something like that too. In my case the graph won't adjust size when the window gets smaller width, but will adjust when the window gets larger width.

Anyway it turns out it's a one liner fix in the css. I will add it to the dev version, and later to master.

**Comment by karlacio** [comment]
> In my case the graph won't adjust size when the window gets smaller width, but will adjust when the window gets larger width.

Yes, this should be the problem.

Thanks for your work!

Carlo.
